import styles from './styles.module.css'
import '../styles/global.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={inter.className}>
      <body className={styles.container}>
      <Header/>
      <main>{children}</main>
      <Footer/>
      </body>
    </html>
  )
}
